version: 2.1



jobs:
  
  configure_infrastructure: 
    docker:
      - image: alpine/ansible
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["8f:90:84:d4:1e:dd:cc:bd:70:c4:75:1d:91:18:c7:7b"] # You can get this ID in the section where you registered the SSH K
      #- run:
       #   name: Install dependencies
        #  command: |
         #   # install the dependencies needed for your playbook
          #  apk add --update ansible 
      
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook main.yml -i inventory.txt 




             
workflows:
  # Name the workflow "welcome"
  Config:
    # Run the welcome/run job in its own container
    jobs:
      #- create_infrastructure 
      - configure_infrastructure
